---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: mybluefin-dx
# description will be included in the image's metadata
description: This is my personal Bluefin OS dx image, with Chrome and 1Password.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: bling
    install:
      - 1password # install 1Password (stable) and `op` CLI tool

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: script
    scripts:
      - enable-chrome-yum-repo.sh

  - type: rpm-ostree
    install:
      - google-chrome-stable
    optfix:
      - google

  - type: dnf
    repos: 
      copr:
        - principis/howdy-beta
    install:
      packages:
        - howdy
        - howdy-gtk